#!/bin/bash

ROOT_PASSWORD=${ROOT_PASSWORD}

NAME=${NAME}
USERNAME=${USERNAME}
PASSWORD=${PASSWORD}

cat << EOF | mysql -u root -p$ROOT_PASSWORD
CREATE DATABASE IF NOT EXISTS $NAME;
GRANT USAGE ON $NAME.* to '$USERNAME'@'%' IDENTIFIED BY '$PASSWORD';
GRANT ALL PRIVILEGES ON $NAME.* TO '$USERNAME'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EXIT
EOF
